### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by micapam** [gtd/validation_scopes#4]
This library is great, especially since you fixed the memory leak! So thanks for all your hard work. Just have one problem and I'm not sure how to work out where it's going wrong...

For my usual validations I can configure error messages via locales e.g. in my config/locales/en.yml I have:

``` en:
  activerecord:
    errors:
      messages:
        blank:      is missing
```

Now the problem is, while for any attributes with normal validations I get the error message I want ('foo is missing'), for any attributes that I validate in a validation_scopes block, I get the standard error message ('bar can't be empty') - ignoring my locale file.

I looked in the source and I couldn't see why this would be. Any ideas?

**Comment by kriskhaira** [comment]
Hi Gabe :) Stumbled upon this while trying to figure out the same thing in Rails 4.2.1 with your gem; so I thought I'd leave a comment for others since this issue is open anyway.

I ended up just using ActiveRecord translations for ActiveModel:

```
  activerecord:
    errors: &model_errors
      models:
        product:
          attributes:
            base:
              name_of_warning: "your warning string here"
   ...
  activemodel:
    errors: *model_errors
```

**Comment by samstickland** [comment]
Hi,

Just starting trying to use this gem and I've ran into this problem straight away too. Can you explain the meaning of:

    errors: &model_errors

and:

    errors: *model_errors

In your yml file above?

I've tried:

```
en:
  activerecord:
    attributes:
      company:
        number: "Company Registration Number"
```

Which translates the attribute number in a normal validation but doesn't work with this gem.
